const actions = {
  LOGIN: 'LOGIN',
  LOADING: 'LOADING',
  REGISTER: 'REGISTER',
  CHECK_LOGIN: 'CHECK_LOGIN',
  GET_QUESTION_DATA: 'GET_QUESTION_DATA',
  GET_FAVORITE_DATA: 'GET_FAVORITE_DATA',
  GET_CATEGORY: 'GET_CATEGORY',
};
export default actions;
