/* Palette generated by Material Palette _ materialpaletteconst com/blue_grey/pink */

const dark_primary_color = '#2666cc';
const default_primary_color = '#3881f7';
// const default_primary_color =  '#f442a1'
const light_primary_color = '#d7e1f2';
const text_primary_color = '#FFFFFF';
const accent_color = '#FFC107';
const primary_text_color = '#212121';
const secondary_text_color = '#757575';
const divider_color = '#BDBDBD';

const correct_answer = '#42f48f';
const wrong_answer = '#ff7a7a';
const gray = '#777777';

/**
 * Rate Us
 */
const RateContentBackground = '#333';
const RateHeaderTextContainerBorderBottom = '#ccc';
const RateHeaderText = '#fff';
const RateText = '#ccc';
const RateDontAskText = '#ccc';
const RateButtonContainerBackground = '#0085ba';
const RateButtonText = '#fff';
const RateCloseButton = '#ccc';

const defaultColors = {
  dark_primary_color,
  default_primary_color,
  light_primary_color,
  text_primary_color,
  accent_color,
  primary_text_color,
  secondary_text_color,
  divider_color,
  correct_answer,
  wrong_answer,
  gray,

  RateContentBackground,
  RateHeaderTextContainerBorderBottom,
  RateHeaderText,
  RateText,
  RateDontAskText,
  RateButtonContainerBackground,
  RateButtonText,
  RateCloseButton,
};

export default {
  ...defaultColors,
};
